### ISSUE TITLE
Uncaught (in promise) Error: No QUIC connection available

### ISSUE THREAD

**Issue by Kmtest-rgb** [open-webrtc-toolkit/owt-server#1104]
Hi
 I am trying to launch  quic agent through owt server.  I am building owt server with quic agent  from source as described in 

https://github.com/open-webrtc-toolkit/owt-server/blob/master/doc/design/quic-agent.md

I got a warning when running scripts/pack.js  --t quic-agent   -t all --install-module --app-path ${webrtc-javascript-sdk-sample-conference-dist}

**Warning: /home/oct18_build/owt-server/source/agent/addons/quicIO/build/Release/quicIO.node not exist**

Is this normal, because I am not sure if --t quicio-agent is needed ?

then when I launch the server, the quic-agent is not launched correctly . I get the following errors in the dist/logs/quic-xx_0.log 

**2021-10-18 22:07:00.024  - ERROR: InternalConnectionRouter - Internal connection router detected error {"purpose":"portal","id":"portal-bd2ff38d7694df5fd2ac@192.168.1.66","type":"worker"}**

Is this because of the quicIO.node error before ?

Now when I go to https://hostname:3004.quic.html  I get the same error as  

https://github.com/open-webrtc-toolkit/owt-server/issues/1058

I am launching chrome with 

google-chrome  --enable-experimental-web-platform-features

I am not sure why I am getting the same error.

I am using the prebuilt certificate.pfx  which is in github.  Do I need to extract the fingerprint from this certificate and add it to the javascript sdk client ?

Can you please help with this issues.

than
![quic_error2](https://user-images.githubusercontent.com/68368997/137858371-6538edbc-8314-45ee-b5ed-f6b1efa7b68b.png)
ks

**Comment by CongyueZhang** [comment]
https://blog.csdn.net/wxl1986622/article/details/107501259

**Comment by Kmtest-rgb** [comment]
Thanks but looks like even before I get to the certificate issue,   I am having issues with running/starting  the quic_agent itself and it is not starting correctly.  I built owt-server from source and also the javascript client for packing from source.  For the quic-sdk I used the pre-built binary from

https://github.com/open-webrtc-toolkit/owt-sdk-quic/actions/runs/1289282605
Pls let me know if there are any issues with this using this version.  I can also try compiling from source.

these are the logs I get from logs/quic-*  log files.   I guess there is a problem with owt.authstore, so quic_agent is launching . I didnt get this error when running Release 5.0 .  
Did you see this issue before ?

thanks

2021-10-19 21:14:43.689  - INFO: WorkingNode - pid: 18167
2021-10-19 21:14:43.692  - INFO: WorkingNode - Connecting to rabbitMQ server...
2021-10-19 21:14:43.748  - DEBUG: AmqpClient - Connect OK
2021-10-19 21:14:43.758  - DEBUG: AmqpClient - Start consume amq.gen-XSrTTuP8oZXwGpPGbzjaGQ owtRpc
2021-10-19 21:14:43.767  - INFO: QuicNode - QUIC transport node.
**2021-10-19 21:14:43.769  - DEBUG: InternalConnectionRouter - Unlock error: { [Error: ENOENT: no such file or directory, open '.owt.authstore']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '.owt.authstore' }**
(node:18167) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
2021-10-19 21:14:43,774  - DEBUG: owt.TransportServer - TCP transport listening on:51415(range:0 ~ 0)
2021-10-19 21:14:43.776  - INFO: QuicNode - path is /home/kumar-pc/dev_ntd_webrtc/dev_2021/server_javascript_5.1/owt-server-5.0.1/dist/quic_agent/cert/certificate.pfx
2021-10-19 21:14:43,779  - DEBUG: QuicTransportServer - QuicTransportServer::QuicTransportServer
2021-10-19 21:14:43,779  - DEBUG: QuicTransportServer - QuicTransportServer::start
[1019/211443.779330:INFO:web_transport_owt_server_impl.cc(117)] WebTransport server is listening [::]:7700
2021-10-19 21:14:43,779  - DEBUG: QuicTransportServer - End of QuicTransportServer::start
2021-10-19 21:14:43.780  - DEBUG: AmqpClient - Setup rpc server ok: quic-849a3725ede17b776239@kumarpc_0
2021-10-19 21:14:43.780  - INFO: WorkingNode - quic-849a3725ede17b776239@kumarpc_0 as rpc server ready
2021-10-19 21:14:43.782  - INFO: WorkingNode - quic-849a3725ede17b776239@kumarpc_0 as monitor ready
2021-10-19 21:17:16.175  - DEBUG: AmqpClient - Received monitoring message: { reason: 'quit',
  message:
   { purpose: 'portal',
     id: 'portal-9785c875ce01ef0de7bf@192.168.1.66',
     type: 'worker' } }
**2021-10-19 21:17:16.176  - ERROR: InternalConnectionRouter - Internal connection router detected error {"purpose":"portal","id":"portal-9785c875ce01ef0de7bf@192.168.1.66","type":"worker"}
2021-10-19 21:20:06.025  - WARN: WorkingNode - Exiting on SIGTERM
2021-10-19 21:20:06.026  - DEBUG: AmqpClient - RpcClient close
2021-10-19 21:20:06.035  - INFO: WorkingNode - Process exit
![quic_error3](https://user-images.githubusercontent.com/68368997/138028477-9cd8e93e-f412-4f33-9acd-1aac31bf4080.png)
**

**Comment by Kmtest-rgb** [comment]
> > > > > > > > > > Hi, this blog gives way to fix the quicIO error. https://blog.csdn.net/wxl1986622/article/details/107501259
> > > > > > > > > > And you need to extract the fingerprint from this certificate and add it to the javascript sdk client. The certificate is valid for three days, so you need to regenerate a new one every three days.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Thanks for the reply .. but is the error Uncaught (in promise) Error: No QUIC connection available , due to quicIO error or is it because of the fingerprint issue ?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > quicIO error I think. I got "net::ERR_QUIC_PROTOCOL_ERROR.QUIC_TLS_CERTIFICATE_UNKNOWN (TLS handshake failure (ENCRYPTION_HANDSHAKE) 46: certificate unknown)" error for the fingerprint issue.
> > > > > > > 
> > > > > > > 
> > > > > > > But when I used the release prebuilt version of owt-server 5.0 (https://github.com/open-webrtc-toolkit/owt-server/releases/tag/v5.0.1) , I dont think I got the quicIO error, but the quic_agent launched correctly I think.
> > > > > > > But I still got the same Uncaught (in promise) Error: No QUIC connection available error.
> > > > > > > So I was not sure if it was because of quicIO or certificate in this case. And since it is the release version of owt server I could not modify the javascript client to change the fingerprint.
> > > > > > 
> > > > > > 
> > > > > > Are you building everything ( owt-server, javascript sdk, owt-quick-sdk) everything from the main branch ?
> > > > > > Did you use this command for extracting the fingerprint
> > > > > > openssl pkcs12 -in certificate.pfx -nodes | openssl x509 -noout -fingerprint
> > > > > > Can you also provide the javascript client file you modified for the fingerprint I tried adding something like this in src/sdk/conference/client.js but got an error.
> > > > > > ```
> > > > > >  * // Following object can be set to conferenceClientConfiguration.webTransportConfiguration. */
> > > > > >     const dict = {
> > > > > >       value: '00:11:22:33:44:55:66:77:88:99:AA:BB:CC:DD:EE:FF:00:11:22:33:44:55:66:77:88:99:AA:BB:CC:DD:EE:FF',
> > > > > >       algorithm: 'sha-256',
> > > > > >     };
> > > > > > this.webTransportConfiguration = dict;
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > thanks
> > > > > 
> > > > > 
> > > > > Yes I build everything from the main branch. And I used the command "openssl x509 -noout -fingerprint -sha256 -inform pem -in out/leaf_cert.pem" to extract the fingerprint. But we have our own windows client. So I didn't fix the fingerprint issue in the javascript client file.
> > > > 
> > > > 
> > > > ok thanks but how did you get cert.pem from certificate.pfx file ?
> > > > from #1058 , the error you were getting was not related to fingerprint issue ? just by changing chrome flags it worked ?
> > > 
> > > 
> > > Use the "openssl pkcs12 -in for-iis.pfx -out for-iis.pem -nodes" command to get pem from pfx. Or you can follow the Certificate Generation steps in the quic-agent.md, you can get the .pem file with the .pfx file.
> > > I found some screenshots about hte fingerprint issue. The error I got in #1058 may not be related to the fingerprint. Sorry I cannot remember clearly.
> > > ![image](https://user-images.githubusercontent.com/53400587/137877187-971926b9-5a0d-45a4-83c0-216c58de3f20.png) ![image](https://user-images.githubusercontent.com/53400587/137877253-5d3254de-d603-4a81-98b2-422d6fecac69.png)
> > 
> > 
> > Thanks but looks like even before I get to the certificate issue, I am having issues with running/starting the quic_agent itself and it is not starting correctly. I built owt-server from source and also the javascript client for packing from source. For the quic-sdk I used the pre-built binary from
> > https://github.com/open-webrtc-toolkit/owt-sdk-quic/actions/runs/1289282605 Pls let me know if there are any issues with this using this version. I can also try compiling from source.
> > these are the logs I get from logs/quic-* log files. I guess there is a problem with owt.authstore, so quic_agent is launching . I didnt get this error when running Release 5.0 . Did you see this issue before ?
> > thanks
> > 2021-10-19 21:14:43.689 - INFO: WorkingNode - pid: 18167 2021-10-19 21:14:43.692 - INFO: WorkingNode - Connecting to rabbitMQ server... 2021-10-19 21:14:43.748 - DEBUG: AmqpClient - Connect OK 2021-10-19 21:14:43.758 - DEBUG: AmqpClient - Start consume amq.gen-XSrTTuP8oZXwGpPGbzjaGQ owtRpc 2021-10-19 21:14:43.767 - INFO: QuicNode - QUIC transport node. **2021-10-19 21:14:43.769 - DEBUG: InternalConnectionRouter - Unlock error: { [Error: ENOENT: no such file or directory, open '.owt.authstore'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.owt.authstore' }** (node:18167) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated 2021-10-19 21:14:43,774 - DEBUG: owt.TransportServer - TCP transport listening on:51415(range:0 ~ 0) 2021-10-19 21:14:43.776 - INFO: QuicNode - path is /home/kumar-pc/dev_ntd_webrtc/dev_2021/server_javascript_5.1/owt-server-5.0.1/dist/quic_agent/cert/certificate.pfx 2021-10-19 21:14:43,779 - DEBUG: QuicTransportServer - QuicTransportServer::QuicTransportServer 2021-10-19 21:14:43,779 - DEBUG: QuicTransportServer - QuicTransportServer::start [1019/211443.779330:INFO:web_transport_owt_server_impl.cc(117)] WebTransport server is listening [::]:7700 2021-10-19 21:14:43,779 - DEBUG: QuicTransportServer - End of QuicTransportServer::start 2021-10-19 21:14:43.780 - DEBUG: AmqpClient - Setup rpc server ok: quic-849a3725ede17b776239@kumarpc_0 2021-10-19 21:14:43.780 - INFO: WorkingNode - quic-849a3725ede17b776239@kumarpc_0 as rpc server ready 2021-10-19 21:14:43.782 - INFO: WorkingNode - quic-849a3725ede17b776239@kumarpc_0 as monitor ready 2021-10-19 21:17:16.175 - DEBUG: AmqpClient - Received monitoring message: { reason: 'quit', message: { purpose: 'portal', id: 'portal-9785c875ce01ef0de7bf@192.168.1.66', type: 'worker' } } **2021-10-19 21:17:16.176 - ERROR: InternalConnectionRouter - Internal connection router detected error {"purpose":"portal","id":"portal-9785c875ce01ef0de7bf@192.168.1.66","type":"worker"} 2021-10-19 21:20:06.025 - WARN: WorkingNode - Exiting on SIGTERM 2021-10-19 21:20:06.026 - DEBUG: AmqpClient - RpcClient close 2021-10-19 21:20:06.035 - INFO: WorkingNode - Process exit ![quic_error3](https://user-images.githubusercontent.com/68368997/138028477-9cd8e93e-f412-4f33-9acd-1aac31bf4080.png) **
> 
> I have the owt.authstore error even after successfully launching the quic agent. Have you fixed the quicIO error?

ok  good to know that quic agent works with the owt.authstore,  so there is a issue somewhere else.

Yes I fixed the quicIO error .  There are two ways, one as your blog suggested .  The other way is to 
add quicIO in the build.js command. I think both do the same thing.  

**scripts/build.js -t quic -t quicIO -t all --check**

But I had to make this change to fix compile error. (I saw this somewhere online) May be can be updated in the instructions.  
  **boost::shared_array<uint8_t> new_buffer;  line 73**
to 
  **boost::shared_array<char> new_buffer;**

but as @jianjunz  suggested before, not sure quicIO which is used for inter agent communication is causing the issue I am facing . May be something else is wrong not sure why portal is reporting error
so my quic_agent not launching correctly.

**Comment by CongyueZhang** [comment]
@WebRTCCoder @Kmtest-rgb  Hello, sorry for the late reply. This is what my colleague sends me. 
![image](https://user-images.githubusercontent.com/53400587/139628368-0c7e7dcc-6b49-4b92-9cb7-44b83ab67c49.png)

**Comment by WebRTCCoder** [comment]
> @WebRTCCoder @Kmtest-rgb Hello, sorry for the late reply. This is what my colleague sends me. ![image](https://user-images.githubusercontent.com/53400587/139628368-0c7e7dcc-6b49-4b92-9cb7-44b83ab67c49.png)

Hi
 Thanks for sharing.  Looks almost like what I have been doing .  I am not sure why  I'm still getting that error. will try again with few things..

**Comment by jianjunz** [comment]
Verification with certificate hash/fingerprint only works for certificates valid for no more than 14 days.

**Comment by WebRTCCoder** [comment]
> Verification with certificate hash/fingerprint only works for certificates valid for no more than 14 days.

Looks like I am still having some issues with certificates. So I have gone back to using the Release v5.0, which is launching and running quic_agent by default.

Pointing to https://localhost://3004/quic.html  with Release v5.0 is not working with latest browser as I guess it is looking for webtransport while v5.0 is using webtransport over" quictransport".

I am not able to downgrade my chrome version to older version, it keeps auto updating, looks like there is no way to do this. So is it not possible to test 
Release v5.0 server with quic transport ?

Can you please let me know if there is any native test application or javascript client test application I can use to test the quic functionility of  Release V5.0 running quic_agent ?

thanks

**Comment by WebRTCCoder** [comment]
> > Verification with certificate hash/fingerprint only works for certificates valid for no more than 14 days.
> 
> Looks like I am still having some issues with certificates. So I have gone back to using the Release v5.0, which is launching and running quic_agent by default.
> 
> Pointing to https://localhost://3004/quic.html with Release v5.0 is not working with latest browser as I guess it is looking for webtransport while v5.0 is using webtransport over" quictransport".
> 
> I am not able to downgrade my chrome version to older version, it keeps auto updating, looks like there is no way to do this. So is it not possible to test Release v5.0 server with quic transport ?
> 
> Can you please let me know if there is any native test application or javascript client test application I can use to test the quic functionility of Release V5.0 running quic_agent ?
> 
> thanks


Hi
  Also  Is there any performance improvement ( latency etc) when using webtransport  vs  quictransport ?

thanks

**Comment by mkumars20** [comment]
Hi @jianjunz  @CongyueZhang 
 I am following this thread and I am doing the same windows client with the 5.0 QUiC Transport server.

But I get the following error after I publish a stream on one client  and then try to subscribe to the stream and receive the data on another client.

**conferenceforwardobserver.cc::114::operator()::Subscribe failed:Timeout to make rpc to conference-375b4933f64a4dceff87@192.168.1.66_0.subscribe
(conferenceclient.cc:1183): Stream removed.**

Looking at the server logs from the quic agent I see this error 
**7c8522d8e0598
[1222/172136.200780:FATAL:sequenced_task_runner_handle.cc(26)] Check failed: current. Error: This caller requires a sequenced context (i.e. the c
urrent task needs to run from a SequencedTaskRunner). If you're in a test refer to //docs/threading_and_tasks_testing.md.
#0 0x7f641d30cca9 <unknown>
..
,,
#24 0x7f641d66e527 QuicTransportStream::write()
#25 0x7f641d66e155 <unknown>
#26 0x000000b917af v8::internal::(anonymous namespace)::HandleApiCallHelper<>()
#27 0x000000b92319 v8::internal::Builtin_HandleApiCall()**



I also built the linux client , but I see this error very rarely and it performs better.
When I use the latest server and client with WebTransport also  I dont see this error.
Happens with windows client and 5.0 QUIC server.

 Can you please let me know what is the issue here?  It complains about the sequenced task runner but from the SDKs looks like the Quic SDK is using single thread runner . 

when I use my windows client to connect to the 5.0 OWT server ( Release version 5.0 downloaded from the webrtc.intel.com) . For building the windows client I used the quic sdk 5.0 version from here   

https://github.com/open-webrtc-toolkit/owt-sdk-quic/releases/tag/v5.0
( I compiled a older chromium version from the DEPS file  92eeac911591a33d319c53313725a157b52d7719)

 and use this to build the  owt client SDK 5.0 
https://github.com/open-webrtc-toolkit/owt-client-native/releases/tag/v5.0


thanks
